# Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

## Setup and Initialization

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# path to csv
csv_path = "Resources/purchase_data.csv"

# read csv and store in a dataframe
purchase_data = pd.read_csv(csv_path) 
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count
* Display the total number of players

In [2]:
# count screennames and print the result
player_count = purchase_data['SN'].count()
player_count

780

## Purchasing Analysis (Total)
* Run basic calculations to obtain number of unique items, average price, etc.
* Create a summary data frame to hold the results
* Optional: give the displayed data cleaner formatting
* Display the summary data frame

In [3]:
# get a list of unique items and count the items in the list
purchase_data_unique_items = purchase_data['Item Name'].value_counts()
len(set(purchase_data_unique_items))

11

In [4]:
# describe the price data and store the table in a dataframe.
# change the data types and formatting
purchase_data_summary = purchase_data.describe()
purchase_data_summary = purchase_data_summary.astype({'Purchase ID': int, 'Age': int, 'Item ID': int, 'Price': float})
pd.options.display.float_format = '{:,.2f}'.format
purchase_data_summary

       Purchase ID  Age  Item ID  Price
count          780  780      780 780.00
mean           389   22       92   3.05
std            225    6       52   1.17
min              0    7        0   1.00
25%            194   20       48   1.98
50%            389   22       93   3.15
75%            584   25      139   4.08
max            779   45      183   4.99

In [5]:
# find total revenue
purchase_data['Price'].sum()

2379.77

## Gender Demographics
* Percentage and Count of Male Players
* Percentage and Count of Female Players
* Percentage and Count of Other / Non-Disclosed

In [6]:
# get a list of totals for different genders
purchase_data_gender = purchase_data['Gender'].value_counts()

# get the male count and divide by the total count.
male_count = purchase_data_gender['Male']
male_percent = male_count / player_count * 100

# get the female count and divide by the total count.
female_count = purchase_data_gender['Female']
female_percent = female_count / player_count * 100

# get the other count and divide by the total count.
other_count = purchase_data_gender['Other / Non-Disclosed']
other_percent = other_count / player_count * 100

# create a dataframe with percents and counts
gender_demographics = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Other / Non-Disclosed'],
    'Percent': [male_percent, female_percent, other_percent],
    'Count': [male_count, female_count, other_count]})
gender_demographics

                  Gender  Percent  Count
0                   Male    83.59    652
1                 Female    14.49    113
2  Other / Non-Disclosed     1.92     15

## Purchasing Analysis (Gender)
* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender
* Create a summary data frame to hold the results
* Optional: give the displayed data cleaner formatting
* Display the summary data frame

In [7]:
# describe the price data for gender groups and store the table in a dataframe.
# change the data type and formatting
purchase_data_gender_summary = purchase_data.groupby('Gender')[['Price']].describe()
purchase_data_gender_summary = purchase_data_gender_summary['Price'].astype({'count': int})
pd.options.display.float_format = '{:,.2f}'.format
purchase_data_gender_summary

                       count  mean  std  min  25%  50%  75%  max
Gender
Female                   113  3.20 1.16 1.00 2.28 3.45 4.23 4.90
Male                     652  3.02 1.18 1.00 1.96 3.09 4.08 4.99
Other / Non-Disclosed     15  3.35 0.88 1.33 3.10 3.45 3.88 4.75

In [8]:
# calculate total purchases by gender group
purchase_data_gender_price_summary = purchase_data.groupby('Gender')[['Price']].sum()
purchase_data_gender_price_summary

                         Price
Gender
Female                  361.94
Male                  1,967.64
Other / Non-Disclosed    50.19

## Age Demographics
* Establish bins for ages
* Categorize the existing players using the age bins. Hint: use pd.cut()
* Calculate the numbers and percentages by age group
* Create a summary data frame to hold the results
* Optional: round the percentage column to two decimal points
* Display Age Demographics Table

In [9]:
# create bins and names
bins = [0, 9, 19, 29, 99]
bin_names = ["9 and younger", "10 to 19", "20 to 29", "30 and older"]

# create a list of ages and apply the bins and names
purchase_data_age_summary = purchase_data[['Age', 'Price']]
purchase_data_age_summary["Age Groups"] = pd.cut(purchase_data_age_summary['Age'], bins, labels = bin_names)
purchase_data_age_summary_unique = purchase_data_age_summary['Age Groups'].value_counts()

# create a grouped summary of the age data
purchase_data_age_summary_group = purchase_data_age_summary.groupby('Age Groups')[['Age']].describe()
purchase_data_age_summary_group = purchase_data_age_summary_group['Age'].astype({'count': int, 'min': int, 'max': int})
pd.options.display.float_format = '{:,.2f}'.format
purchase_data_age_summary_group

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

               count  mean  std  min   25%   50%   75%  max
Age Groups
9 and younger     23  7.87 0.81    7  7.00  8.00  8.50    9
10 to 19         164 15.87 2.48   10 15.00 16.00 18.00   19
20 to 29         466 22.74 2.25   20 21.00 23.00 24.00   29
30 and older     127 34.14 3.82   30 30.00 33.00 37.00   45

## Purchasing Analysis (Age)
* Bin the purchase_data data frame by age
* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below
* Create a summary data frame to hold the results
* Optional: give the displayed data cleaner formatting
* Display the summary data frame

In [10]:
# describe the price data for age groups and store the table in a dataframe.
# change the data types and formatting
purchase_data_price_summary_group = purchase_data_age_summary.groupby('Age Groups')[['Price']].describe()
purchase_data_price_summary_group = purchase_data_price_summary_group['Price'].astype({'count': int})
pd.options.display.float_format = '{:,.2f}'.format
purchase_data_price_summary_group

               count  mean  std  min  25%  50%  75%  max
Age Groups
9 and younger     23  3.35 1.07 1.29 2.51 3.39 4.28 4.93
10 to 19         164  3.02 1.16 1.01 2.03 3.08 4.18 4.94
20 to 29         466  3.02 1.18 1.00 1.94 3.16 4.03 4.99
30 and older     127  3.15 1.17 1.02 2.05 3.33 4.23 4.93

In [11]:
# show price data for each age
purchase_data_each_age_summary = purchase_data.groupby('Age')[['Price']].describe()
purchase_data_each_age_summary = purchase_data_each_age_summary['Price'].astype({'count': int})
pd.options.display.float_format = '{:,.2f}'.format
purchase_data_each_age_summary

     count  mean  std  min  25%  50%  75%  max
Age
7        9  3.65 0.88 2.38 3.08 4.19 4.32 4.60
8        8  3.25 1.43 1.29 1.94 3.56 4.29 4.93
9        6  3.04 0.81 2.05 2.59 2.96 3.31 4.40
10       9  3.54 0.84 1.75 3.10 3.74 4.18 4.35
11       7  2.68 1.21 1.61 1.71 1.97 3.78 4.24
12       6  2.63 0.87 1.56 1.99 2.60 3.44 3.54
13       4  2.36 1.11 1.03 1.92 2.33 2.78 3.75
14       2  3.46 2.10 1.97 2.71 3.46 4.20 4.94
15      35  3.02 1.23 1.01 2.08 2.94 4.36 4.88
16      30  3.02 1.22 1.03 2.21 2.79 4.35 4.90
17      22  2.93 1.25 1.28 1.75 2.44 4.13 4.91
18      26  3.16 1.03 1.40 2.23 3.27 3.80 4.90
19      23  3.04 1.24 1.02 2.08 3.08 4.25 4.91
20      99  3.17 1.16 1.00 2.05 3.46 4.21 4.93
21      62  2.92 1.19 1.01 1.76 3.02 3.82 4.94
22      70  2.96 1.17 1.02 1.90 3.05 3.85 4.99
23      67  3.01 1.23 1.01 1.79 3.16 4.05 4.99
24      67  3.14 1.17 1.02 2.20 3.19 4.13 4.94
25      59  3.08 1.15 1.00 2.35 3.19 3.86 4.94
26      14  2.87 1.12 1.44 1.84 2.69 3.56 4.94
27      10  2.72 1.08 1.14 1.90 2.69 3.43 4.64
28       5  1.69 0.64 1.14 1.14 1.41 2.28 2.48
29      13  2.71 1.26 1.09 1.70 2.48 3.74 4.90
30      35  3.15 1.27 1.02 1.96 3.33 4.24 4.93
31       7  3.44 1.12 1.76 2.71 3.58 4.20 4.89
32       8  2.84 0.95 1.16 2.21 3.12 3.44 4.00
33      14  2.49 1.02 1.06 1.60 2.33 3.38 4.23
34       9  2.46 0.89 1.02 2.05 2.49 3.09 3.65
35      14  3.72 0.90 1.98 3.53 3.84 4.38 4.86
36       5  2.53 1.09 1.60 1.71 2.18 2.94 4.23
37       7  3.64 1.09 1.79 3.15 3.44 4.54 4.90
38       9  3.79 1.08 1.75 3.10 4.35 4.40 4.89
39       6  3.89 0.88 2.85 3.23 3.76 4.68 4.91
40       6  2.79 1.39 1.33 1.62 2.59 4.02 4.40
41       2  3.27 2.35 1.61 2.44 3.27 4.10 4.93
42       1  3.93  nan 3.93 3.93 3.93 3.93 3.93
43       1  4.00  nan 4.00 4.00 4.00 4.00 4.00
44       2  2.68 1.00 1.97 2.33 2.68 3.04 3.39
45       1  1.70  nan 1.70 1.70 1.70 1.70 1.70

## Top Spenders
* Run basic calculations to obtain the results in the table below
* Create a summary data frame to hold the results
* Sort the total purchase value column in descending order
* Optional: give the displayed data cleaner formatting
* Display a preview of the summary data frame

In [12]:
# sort purchase data by highest amount spent by a user
purchase_data[['SN', 'Price']].sort_values('Price', ascending=False).nlargest(20, 'Price')

                 SN  Price
554        Dyally87   4.99
189        Hiasri33   4.99
110         Ririp86   4.94
246      Lirtilsa71   4.94
493   Chanirrasta87   4.94
116    Lassilsala30   4.94
231  Yarithsurgue62   4.94
477      Mindossa76   4.93
686      Chadjask77   4.93
290     Idastidru52   4.93
275     Smaistysu35   4.93
312     Strithenu87   4.93
577      Filurarn35   4.91
593      Lassimla92   4.91
388          Aeda94   4.91
284         Firan91   4.91
517  Aerithnuphos61   4.91
666      Assilsan72   4.90
504    Chamilsala65   4.90
240    Lirtastsda29   4.90

## Most Popular Items
* Retrieve the Item ID, Item Name, and Item Price columns
* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value
* Create a summary data frame to hold the results
* Sort the purchase count column in descending order
* Display a preview of the summary data frame

In [13]:
# create a dataframe with Item ID, Item Name, and Price
purchase_data_ID_Name_Price = purchase_data[['Item ID', 'Item Name', 'Price']]
purchase_data_ID_Name_Price.groupby(['Item ID', 'Item Name']).size().reset_index(name='Total Count').sort_values('Total Count', ascending = False)

     Item ID                                     Item Name  Total Count
177      178  Oathbreaker, Last Hope of the Breaking Storm           12
144      145                          Fiery Glass Crusader            9
107      108     Extraction, Quickblade Of Trembling Hands            9
81        82                                       Nirvana            9
19        19                 Pursuit, Cudgel of Necromancy            8
102      103                                Singed Scalpel            8
74        75                       Brutality Ivory Warmace            8
71        72                                 Winter's Bite            8
59        60                                          Wolf            8
58        59                 Lightning, Etcher of the King            8
36        37           Shadow Strike, Glory of Ending Hope            8
34        34                               Retribution Axe            8
91        92                                  Final Critic            8
52        53                             Vengeance Cleaver            7
109      110                                    Suspension            7
7          7                  Thorn, Satchel of Dark Souls            7
70        71                                        Demise            7
116      117             Heartstriker, Legacy of the Light            7
158      159             Oathbreaker, Spellblade of Trials            7
84        85                                Malificent Bag            7
163      164                              Exiled Doomblade            7
140      141                                    Persuasion            7
77        78                    Glimmer, Ender of the Moon            7
101      102                                       Avenger            6
128      129            Fate, Vengeance of Eternal Justice            6
92        93                      Apocalyptic Battlescythe            6
53        54                               Eternal Cleaver            6
3          3                                  Phantomlight            6
2          2                                       Verdict            6
39        40                                 Second Chance            6
..       ...                                           ...          ...
80        81                                     Dreamkiss            2
6          6                                   Rusty Skull            2
18        18                    Torchlight, Bond of Storms            2
26        26                                   Unholy Wand            2
28        28              Flux, Destroyer of Due Diligence            2
30        30                                   Stormcaller            2
157      158            Darkheart, Butcher of the Champion            2
68        69               Frenzy, Defender of the Harvest            2
131      132                                    Persuasion            2
62        63                                Stormfury Mace            2
55        56                      Foul Titanium Battle Axe            2
126      127                  Heartseeker, Reaver of Souls            2
47        48               Rage, Legacy of the Lone Victor            2
124      125                    Whistling Mithril Warblade            2
42        43                                     Foul Edge            2
114      115                    Spectral Diamond Doomblade            2
33        33                                    Curved Axe            2
31        31                                     Trickster            2
117      118              Ghost Reaver, Longsword of Magic            1
46        47                   Alpha, Reach of Ending Hope            1
41        42                               The Decapitator            1
27        27               Riddle, Tribute of Ended Dreams            1
125      126                      Exiled Mithril Longsword            1
50        51                                    Endbringer            1
89        90                                      Betrayer            1
103      104                            Gladiator's Glaive            1
23        23                                      Crucifer            1
179      180                                   Stormcaller            1
90        91                                       Celeste            1
133      134                               Undead Crusader            1

[183 rows x 3 columns]

In [14]:
# group by item name and sort by price
purchase_data_ID_Name_Price.groupby(['Item Name']).apply(lambda x: x.sort_values(['Price'], ascending = False))

                                              Item ID  \
Item Name
Abyssal Shard                            7        162
                                         11       162
                                         209      162
                                         403      162
                                         510      162
Aetherius, Boon of the Blessed           214      137
                                         248      137
                                         369      137
                                         575      137
                                         631      137
Agatha                                   130      120
                                         211      120
                                         415      120
                                         432      120
                                         447      120
                                         670      120
Alpha                                    673      130
                                         699      130
                                         765      130
Alpha, Oath of Zeal                      352       79
                                         496       79
                                         754       79
Alpha, Reach of Ending Hope              664       47
Amnesia                                  50        22
                                         144       22
                                         491       22
                                         542       22
                                         638       22
                                         644       22
Apocalyptic Battlescythe                 413       93
...                                               ...
Winterthorn, Defender of Shifting Worlds 723      177
Woeful Adamantite Claymore               142      175
                                         221      175
                                         257      175
Wolf                                     52        60
                                         90        60
                                         141       60
                                         394       60
                                         479       60
                                         550       60
                                         661       60
                                         775       60
Wolf, Promise of the Moonwalker          31       179
                                         137      179
                                         305      179
                                         429      179
                                         481      179
                                         565      179
Worldbreaker                             466      112
                                         537      112
                                         691      112
                                         752      112
Yearning Crusher                         129       74
                                         358       74
                                         729       74
Yearning Mageblade                       200      114
                                         232      114
                                         333      114
                                         623      114
                                         645      114

                                                                             Item Name  \
Item Name
Abyssal Shard                            7                               Abyssal Shard
                                         11                              Abyssal Shard
                                         209                             Abyssal Shard
                                         403                             Abyssal Shard
                                         510                             Abyssal Shard
Aetherius, Boon of the Blessed           214            Aetherius, Boon of the Blessed
                                         248            Aetherius, Boon of the Blessed
                                         369            Aetherius, Boon of the Blessed
                                         575            Aetherius, Boon of the Blessed
                                         631            Aetherius, Boon of the Blessed
Agatha                                   130                                    Agatha
                                         211                                    Agatha
                                         415                                    Agatha
                                         432                                    Agatha
                                         447                                    Agatha
                                         670                                    Agatha
Alpha                                    673                                     Alpha
                                         699                                     Alpha
                                         765                                     Alpha
Alpha, Oath of Zeal                      352                       Alpha, Oath of Zeal
                                         496                       Alpha, Oath of Zeal
                                         754                       Alpha, Oath of Zeal
Alpha, Reach of Ending Hope              664               Alpha, Reach of Ending Hope
Amnesia                                  50                                    Amnesia
                                         144                                   Amnesia
                                         491                                   Amnesia
                                         542                                   Amnesia
                                         638                                   Amnesia
                                         644                                   Amnesia
Apocalyptic Battlescythe                 413                  Apocalyptic Battlescythe
...                                                                                ...
Winterthorn, Defender of Shifting Worlds 723  Winterthorn, Defender of Shifting Worlds
Woeful Adamantite Claymore               142                Woeful Adamantite Claymore
                                         221                Woeful Adamantite Claymore
                                         257                Woeful Adamantite Claymore
Wolf                                     52                                       Wolf
                                         90                                       Wolf
                                         141                                      Wolf
                                         394                                      Wolf
                                         479                                      Wolf
                                         550                                      Wolf
                                         661                                      Wolf
                                         775                                      Wolf
Wolf, Promise of the Moonwalker          31            Wolf, Promise of the Moonwalker
                                         137           Wolf, Promise of the Moonwalker
                                         305           Wolf, Promise of the Moonwalker
                                         429           Wolf, Promise of the Moonwalker
                                         481           Wolf, Promise of the Moonwalker
                                         565           Wolf, Promise of the Moonwalker
Worldbreaker                             466                              Worldbreaker
                                         537                              Worldbreaker
                                         691                              Worldbreaker
                                         752                              Worldbreaker
Yearning Crusher                         129                          Yearning Crusher
                                         358                          Yearning Crusher
                                         729                          Yearning Crusher
Yearning Mageblade                       200                        Yearning Mageblade
                                         232                        Yearning Mageblade
                                         333                        Yearning Mageblade
                                         623                        Yearning Mageblade
                                         645                        Yearning Mageblade

                                              Price
Item Name
Abyssal Shard                            7     2.67
                                         11    2.67
                                         209   2.67
                                         403   2.67
                                         510   2.67
Aetherius, Boon of the Blessed           214   3.39
                                         248   3.39
                                         369   3.39
                                         575   3.39
                                         631   3.39
Agatha                                   130   3.08
                                         211   3.08
                                         415   3.08
                                         432   3.08
                                         447   3.08
                                         670   3.08
Alpha                                    673   2.07
                                         699   2.07
                                         765   2.07
Alpha, Oath of Zeal                      352   4.05
                                         496   4.05
                                         754   4.05
Alpha, Reach of Ending Hope              664   3.58
Amnesia                                  50    2.18
                                         144   2.18
                                         491   2.18
                                         542   2.18
                                         638   2.18
                                         644   2.18
Apocalyptic Battlescythe                 413   1.97
...                                             ...
Winterthorn, Defender of Shifting Worlds 723   2.08
Woeful Adamantite Claymore               142   4.48
                                         221   4.48
                                         257   4.48
Wolf                                     52    3.54
                                         90    3.54
                                         141   3.54
                                         394   3.54
                                         479   3.54
                                         550   3.54
                                         661   3.54
                                         775   3.54
Wolf, Promise of the Moonwalker          31    4.48
                                         137   4.48
                                         305   4.48
                                         429   4.48
                                         481   4.48
                                         565   4.48
Worldbreaker                             466   2.60
                                         537   2.60
                                         691   2.60
                                         752   2.60
Yearning Crusher                         129   4.18
                                         358   4.18
                                         729   4.18
Yearning Mageblade                       200   3.82
                                         232   3.82
                                         333   3.82
                                         623   3.82
                                         645   3.82

[780 rows x 3 columns]

In [15]:
# group by item id and sort by total price
purchase_data_ID_Name_Price.groupby(['Item ID', 'Item Name']).sum().sort_values('Price')

                                                      Price
Item ID Item Name
42      The Decapitator                                1.75
104     Gladiator's Glaive                             1.93
23      Crucifer                                       1.99
126     Exiled Mithril Longsword                       2.00
125     Whistling Mithril Warblade                     2.00
28      Flux, Destroyer of Due Diligence               2.12
118     Ghost Reaver, Longsword of Magic               2.17
26      Unholy Wand                                    2.24
33      Curved Axe                                     2.32
90      Betrayer                                       2.94
168     Sun Strike, Jaws of Twisted Visions            2.96
31      Trickster                                      3.10
183     Dragon's Greatsword                            3.27
27      Riddle, Tribute of Ended Dreams                3.30
180     Stormcaller                                    3.36
47      Alpha, Reach of Ending Hope                    3.58
69      Frenzy, Defender of the Harvest                3.96
115     Spectral Diamond Doomblade                     4.08
70      Hope's End                                     4.12
177     Winterthorn, Defender of Shifting Worlds       4.16
91      Celeste                                        4.17
135     Warped Diamond Crusader                        4.20
30      Stormcaller                                    4.42
134     Undead Crusader                                4.50
51      Endbringer                                     4.66
158     Darkheart, Butcher of the Champion             4.90
48      Rage, Legacy of the Lone Victor                4.96
155     War-Forged Gold Deflector                      5.05
0       Splinter                                       5.12
124     Venom Claymore                                 5.16
...                                                     ...
52      Hatred                                        19.36
75      Brutality Ivory Warmace                       19.36
165     Bone Crushing Silver Skewer                   19.44
111     Misery's End                                  19.56
39      Betrayal, Whisper of Grieving Widows          19.70
133     Faith's Scimitar                              20.45
102     Avenger                                       20.64
101     Final Critic                                  20.95
65      Conqueror Adamantite Mace                     21.20
136     Ghastly Adamantite Protector                  21.48
159     Oathbreaker, Spellblade of Trials             21.56
87      Deluge, Edge of the West                      22.15
141     Persuasion                                    22.33
138     Peacekeeper, Wit of Dark Magic                23.70
128     Blazeguard, Reach of Eternity                 24.55
139     Mercy, Katana of Dismay                       24.70
37      Shadow Strike, Glory of Ending Hope           25.28
25      Hero Cane                                     26.10
160     Azurewrath                                    26.40
179     Wolf, Promise of the Moonwalker               26.88
60      Wolf                                          28.32
72      Winter's Bite                                 30.16
78      Glimmer, Ender of the Moon                    30.80
108     Extraction, Quickblade Of Trembling Hands     31.77
59      Lightning, Etcher of the King                 33.84
103     Singed Scalpel                                34.80
92      Final Critic                                  39.04
145     Fiery Glass Crusader                          41.22
82      Nirvana                                       44.10
178     Oathbreaker, Last Hope of the Breaking Storm  50.76

[183 rows x 1 columns]

## Most Profitable Items

* Sort the above table by total purchase value in descending order
* Optional: give the displayed data cleaner formatting
* Display a preview of the data frame

In [16]:
# group by item id and sort by total price descending
purchase_data_ID_Name_Price.groupby(['Item ID', 'Item Name']).sum().sort_values('Price', ascending = False)

                                                      Price
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm  50.76
82      Nirvana                                       44.10
145     Fiery Glass Crusader                          41.22
92      Final Critic                                  39.04
103     Singed Scalpel                                34.80
59      Lightning, Etcher of the King                 33.84
108     Extraction, Quickblade Of Trembling Hands     31.77
78      Glimmer, Ender of the Moon                    30.80
72      Winter's Bite                                 30.16
60      Wolf                                          28.32
179     Wolf, Promise of the Moonwalker               26.88
160     Azurewrath                                    26.40
25      Hero Cane                                     26.10
37      Shadow Strike, Glory of Ending Hope           25.28
139     Mercy, Katana of Dismay                       24.70
128     Blazeguard, Reach of Eternity                 24.55
138     Peacekeeper, Wit of Dark Magic                23.70
141     Persuasion                                    22.33
87      Deluge, Edge of the West                      22.15
159     Oathbreaker, Spellblade of Trials             21.56
136     Ghastly Adamantite Protector                  21.48
65      Conqueror Adamantite Mace                     21.20
101     Final Critic                                  20.95
102     Avenger                                       20.64
133     Faith's Scimitar                              20.45
39      Betrayal, Whisper of Grieving Widows          19.70
111     Misery's End                                  19.56
165     Bone Crushing Silver Skewer                   19.44
75      Brutality Ivory Warmace                       19.36
52      Hatred                                        19.36
...                                                     ...
124     Venom Claymore                                 5.16
0       Splinter                                       5.12
155     War-Forged Gold Deflector                      5.05
48      Rage, Legacy of the Lone Victor                4.96
158     Darkheart, Butcher of the Champion             4.90
51      Endbringer                                     4.66
134     Undead Crusader                                4.50
30      Stormcaller                                    4.42
135     Warped Diamond Crusader                        4.20
91      Celeste                                        4.17
177     Winterthorn, Defender of Shifting Worlds       4.16
70      Hope's End                                     4.12
115     Spectral Diamond Doomblade                     4.08
69      Frenzy, Defender of the Harvest                3.96
47      Alpha, Reach of Ending Hope                    3.58
180     Stormcaller                                    3.36
27      Riddle, Tribute of Ended Dreams                3.30
183     Dragon's Greatsword                            3.27
31      Trickster                                      3.10
168     Sun Strike, Jaws of Twisted Visions            2.96
90      Betrayer                                       2.94
33      Curved Axe                                     2.32
26      Unholy Wand                                    2.24
118     Ghost Reaver, Longsword of Magic               2.17
28      Flux, Destroyer of Due Diligence               2.12
125     Whistling Mithril Warblade                     2.00
126     Exiled Mithril Longsword                       2.00
23      Crucifer                                       1.99
104     Gladiator's Glaive                             1.93
42      The Decapitator                                1.75

[183 rows x 1 columns]